### ISSUE TITLE
permitremoteopen not working

### ISSUE THREAD

**Issue by deepam1982** [antonyantony/openssh#2]
I have ubuntu micro instance on aws which by default had openssh6.1.1p1. I cloned the master and installed this branch on the machine(./configure make).
ssh -V
OpenSSH_7.1p1, OpenSSL 1.0.1f 6 Jan 2014
so far so good
then I edited /etc/ssh/sshd_config, and added  "PermitRemoteOpen 8080" at the end of it
After that when I tried to reload config it resulted in ssh job crash
sudo service ssh reload
reload: Job is not running: ssh

**Comment by antonyantony** [comment]
PermitRemoteOpen 8080 is works
