### ISSUE TITLE
permitremoteopen with multiple ports

### ISSUE THREAD

**Issue by dmatic** [antonyantony/openssh#3]
Hi, is it possible to list multiple ports with permitremoteopen restriction? I've tried `permitremoteopen="xxx,yyy" ssh-rsa...` and `permitremoteopen="xxx","yyy" ssh-rsa...` , but it only recognizes `permitremoteopen="xxx" ssh-rsa` option, with all other combinations I get `Permission denied (publickey).` error. 

Also, is it possible to terminate a connection when the port doesn't match? I get the `Warning: remote port forwarding failed for listen port ZZZZZ`. but the connection is not terminated afterwards.

**Comment by antonyantony** [comment]
multiple ports forwarding are allowed. 
syntax is : permitremoteopen="8080",permitremoteopen="8081" ssh-rsa AAAAB3NzaC

ssh -v -R 8080:127.0.0.1:22 -R 8081:127.0.0.1:22 -p 2022 user@server
debug1: remote forward success for: listen 8080, connect 127.0.0.1:22
debug1: remote forward success for: listen 8081, connect 127.0.0.1:22

terminating when forward fails is not easy. port forward can be initiated after the session is established too. Not all forwards are at the beginning. Some may fail and some succeed it is not possible to terminated a ssh session based on failure to forward. This is the behavior of permitopen, permitremoteopen is based on permitopen.
